const ARMORS = [
  // --- COMMON ARMOR ---
  {
    key: 'leather_helm',
    name: 'Leather Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'head',
    baseType: 'Helm',
    val: 3,
    stat: 'Armor',
    price: 25,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'leather_boots',
    name: 'Leather Boots',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shins',
    baseType: 'Greaves',
    val: 3,
    stat: 'Armor',
    price: 20,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'padded_vest',
    name: 'Padded Vest',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 4,
    stat: 'Armor',
    price: 30,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'cloth_hood',
    name: 'Cloth Hood',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'head',
    baseType: 'Hood',
    val: 2,
    stat: 'Armor',
    price: 15,
    minShopLevel: 1,
    statMods: { mag: 1 }
  },
  {
    key: 'travelers_cloak',
    name: "Traveler's Cloak",
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shoulders',
    baseType: 'Cloak',
    val: 3,
    stat: 'Armor',
    price: 22,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'worn_bracers',
    name: 'Worn Bracers',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'arms',
    baseType: 'Bracers',
    val: 3,
    stat: 'Armor',
    price: 20,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'stitched_greaves',
    name: 'Stitched Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shins',
    baseType: 'Greaves',
    val: 4,
    stat: 'Armor',
    price: 28,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'buckler_shield',
    name: 'Buckler Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shield',
    baseType: 'Shield',
    val: 4,
    stat: 'Armor',
    price: 30,
    minShopLevel: 1,
    statMods: { def: 1 }
  },
  {
    key: 'quilted_pants',
    name: 'Quilted Pants',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shins',
    baseType: 'Leggings',
    val: 3,
    stat: 'Armor',
    price: 23,
    minShopLevel: 1,
    statMods: { vit: 1 }
  },
  {
    key: 'guards_tunic',
    name: "Guard's Tunic",
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 4,
    stat: 'Armor',
    price: 32,
    minShopLevel: 1,
    statMods: { def: 1 }
  },

  // --- UNCOMMON ARMOR ---
  {
    key: 'iron_chest',
    name: 'Iron Chestplate',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 7,
    stat: 'Armor',
    price: 70,
    minShopLevel: 2,
    statMods: { vit: 1 }
  },
  {
    key: 'iron_gauntlets',
    name: 'Iron Gauntlets',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'arms',
    baseType: 'Gauntlets',
    val: 5,
    stat: 'Armor',
    price: 55,
    minShopLevel: 2,
    statMods: { atk: 1 }
  },
  {
    key: 'iron_greaves',
    name: 'Iron Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shins',
    baseType: 'Greaves',
    val: 6,
    stat: 'Armor',
    price: 60,
    minShopLevel: 2,
    statMods: { def: 1 }
  },
  {
    key: 'chain_hood',
    name: 'Chain Hood',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'head',
    baseType: 'Coif',
    val: 6,
    stat: 'Armor',
    price: 70,
    minShopLevel: 2,
    statMods: { def: 1 }
  },
  {
    key: 'chain_boots',
    name: 'Chain Boots',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shins',
    baseType: 'Sabatons',
    val: 6,
    stat: 'Armor',
    price: 72,
    minShopLevel: 2,
    statMods: { vit: 1 }
  },
  {
    key: 'reinforced_bracers',
    name: 'Reinforced Bracers',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'arms',
    baseType: 'Bracers',
    val: 5,
    stat: 'Armor',
    price: 65,
    minShopLevel: 2,
    statMods: { atk: 1, def: 1 }
  },
  {
    key: 'scout_mantle',
    name: 'Scout Mantle',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shoulders',
    baseType: 'Mantle',
    val: 5,
    stat: 'Armor',
    price: 60,
    minShopLevel: 2,
    statMods: { chr: 1, atk: 1 }
  },
  {
    key: 'kite_shield',
    name: 'Kite Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shield',
    baseType: 'Shield',
    val: 8,
    stat: 'Armor',
    price: 80,
    minShopLevel:1,
    statMods: { def: 2 },
  },
  {
    key: 'brigand_vest',
    name: 'Brigand Vest',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'chest',
    baseType: 'Vest',
    val: 6,
    stat: 'Armor',
    price: 68,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'sentry_mask',
    name: 'Sentry Mask',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'head',
    baseType: 'Mask',
    val: 5,
    stat: 'Armor',
    price: 62,
    minShopLevel: 2,
    statMods: { chr: 1, def: 1 }
  },

  // --- RARE ARMOR ---
  {
    key: 'guardian_shield',
    name: 'Guardian Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shield',
    baseType: 'Shield',
    val: 10,
    stat: 'Armor',
    price: 120,
    minShopLevel: 3,
    statMods: { def: 2 }
  },
  {
    key: 'battle_mantle',
    name: 'Battle Mantle',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shoulders',
    baseType: 'Pauldrons',
    val: 8,
    stat: 'Armor',
    price: 110,
    minShopLevel: 3,
    statMods: { str: 2 }
  },
  {
    key: 'mage_robe',
    name: "Mage's Robe",
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'chest',
    baseType: 'Robe',
    val: 6,
    stat: 'Armor',
    price: 115,
    minShopLevel: 3,
    statMods: { mag: 3 }
  },
  {
    key: 'lion_helm',
    name: 'Lion Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'head',
    baseType: 'Helm',
    val: 9,
    stat: 'Armor',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 2, vit: 1 }
  },
  {
    key: 'warlord_cuirass',
    name: 'Warlord Cuirass',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'chest',
    baseType: 'Cuirass',
    val: 11,
    stat: 'Armor',
    price: 145,
    minShopLevel: 3,
    statMods: { vit: 2, def: 1 }
  },
  {
    key: 'spellbinder_gloves',
    name: 'Spellbinder Gloves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'arms',
    baseType: 'Gloves',
    val: 7,
    stat: 'Armor',
    price: 125,
    minShopLevel: 3,
    statMods: { mag: 3 }
  },
  {
    key: 'shadowstep_boots',
    name: 'Shadowstep Boots',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shins',
    baseType: 'Boots',
    val: 8,
    stat: 'Armor',
    price: 130,
    minShopLevel: 3,
    statMods: { atk: 1, chr: 2 }
  },
  {
    key: 'siege_greaves',
    name: 'Siege Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shins',
    baseType: 'Greaves',
    val: 9,
    stat: 'Armor',
    price: 135,
    minShopLevel: 3,
    statMods: { def: 2, vit: 1 }
  },
  {
    key: 'radiant_cape',
    name: 'Radiant Cape',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shoulders',
    baseType: 'Cape',
    val: 8,
    stat: 'Armor',
    price: 128,
    minShopLevel: 3,
    statMods: { chr: 2, mag: 1 }
  },
  {
    key: 'mirror_shield',
    name: 'Mirror Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shield',
    baseType: 'Shield',
    val: 11,
    stat: 'Armor',
    price: 150,
    minShopLevel: 3,
    statMods: { def: 3 }
  },

  // --- EPIC ARMOR ---
  {
    key: 'oathbound_helm',
    name: 'Oathbound Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'head',
    baseType: 'Helm',
    val: 11,
    stat: 'Armor',
    price: 200,
    minShopLevel: 4,
    statMods: { vit: 2, def: 1 }
  },
  {
    key: 'stormplate',
    name: 'Stormplate Armor',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'chest',
    baseType: 'Breastplate',
    val: 14,
    stat: 'Armor',
    price: 230,
    minShopLevel: 4,
    statMods: { vit: 2, str: 1 }
  },
  {
    key: 'veilwalkers_boots',
    name: "Veilwalker's Boots",
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shins',
    baseType: 'Greaves',
    val: 10,
    stat: 'Armor',
    price: 210,
    minShopLevel: 4,
    statMods: { chr: 2, atk: 1 }
  },
  {
    key: 'dreadlords_visor',
    name: "Dreadlord's Visor",
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'head',
    baseType: 'Helm',
    val: 13,
    stat: 'Armor',
    price: 230,
    minShopLevel: 4,
    statMods: { def: 2, chr: 1 }
  },
  {
    key: 'heartforge_mail',
    name: 'Heartforge Mail',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'chest',
    baseType: 'Mail',
    val: 15,
    stat: 'Armor',
    price: 250,
    minShopLevel: 4,
    statMods: { vit: 3, def: 1 }
  },
  {
    key: 'thunderbound_gauntlets',
    name: 'Thunderbound Gauntlets',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'arms',
    baseType: 'Gauntlets',
    val: 12,
    stat: 'Armor',
    price: 225,
    minShopLevel: 4,
    statMods: { str: 2, atk: 2 }
  },
  {
    key: 'skystride_greaves',
    name: 'Skystride Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shins',
    baseType: 'Greaves',
    val: 13,
    stat: 'Armor',
    price: 235,
    minShopLevel: 4,
    statMods: { vit: 2, atk: 1 }
  },
  {
    key: 'phoenix_cloak',
    name: 'Phoenix Cloak',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shoulders',
    baseType: 'Cloak',
    val: 12,
    stat: 'Armor',
    price: 220,
    minShopLevel: 4,
    statMods: { mag: 2, chr: 2 }
  },
  {
    key: 'spellweave_robes',
    name: 'Spellweave Robes',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'chest',
    baseType: 'Robe',
    val: 11,
    stat: 'Armor',
    price: 225,
    minShopLevel: 4,
    statMods: { mag: 4 }
  },
  {
    key: 'bulwark_of_twilight',
    name: 'Bulwark of Twilight',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shield',
    baseType: 'Shield',
    val: 15,
    stat: 'Armor',
    price: 255,
    minShopLevel: 4,
    statMods: { def: 3, vit: 2 }
  },

  // --- LEGENDARY ARMOR ---
  {
    key: 'dragon_greaves',
    name: 'Dragon Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shins',
    baseType: 'Greaves',
    val: 15,
    stat: 'Armor',
    price: 350,
    minShopLevel: 5,
    statMods: { vit: 2 }
  },
  {
    key: 'aegis_of_kings',
    name: 'Aegis of Kings',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shield',
    baseType: 'Shield',
    val: 18,
    stat: 'Armor',
    price: 420,
    minShopLevel: 6,
    statMods: { def: 4, vit: 2 }
  },
  {
    key: 'crown_of_the_void',
    name: 'Crown of the Void',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'head',
    baseType: 'Crown',
    val: 12,
    stat: 'Armor',
    price: 380,
    minShopLevel: 6,
    statMods: { mag: 4, chr: 3 }
  },
  {
    key: 'starlight_ward',
    name: 'Starlight Ward',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shoulders',
    baseType: 'Mantle',
    val: 14,
    stat: 'Armor',
    price: 360,
    minShopLevel: 5,
    statMods: { mag: 3, chr: 3 }
  },
  {
    key: 'tyrants_carapace',
    name: "Tyrant's Carapace",
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'chest',
    baseType: 'Plate',
    val: 18,
    stat: 'Armor',
    price: 410,
    minShopLevel: 6,
    statMods: { vit: 3, def: 3 }
  },
  {
    key: 'mask_of_the_depths',
    name: 'Mask of the Depths',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'head',
    baseType: 'Mask',
    val: 15,
    stat: 'Armor',
    price: 380,
    minShopLevel: 6,
    statMods: { mag: 4, def: 2 }
  },
  {
    key: 'celestial_sabatons',
    name: 'Celestial Sabatons',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shins',
    baseType: 'Sabatons',
    val: 16,
    stat: 'Armor',
    price: 390,
    minShopLevel: 5,
    statMods: { vit: 3, chr: 2 }
  },
  {
    key: 'mantle_of_eternity',
    name: 'Mantle of Eternity',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shoulders',
    baseType: 'Cape',
    val: 15,
    stat: 'Armor',
    price: 385,
    minShopLevel: 6,
    statMods: { mag: 3, vit: 2 }
  },
  {
    key: 'gauntlets_of_rage',
    name: 'Gauntlets of Rage',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'arms',
    baseType: 'Gauntlets',
    val: 14,
    stat: 'Armor',
    price: 370,
    minShopLevel: 5,
    statMods: { str: 4, atk: 3 }
  },
  {
    key: 'dragonheart_aegis',
    name: 'Dragonheart Aegis',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shield',
    baseType: 'Shield',
    val: 20,
    stat: 'Armor',
    price: 430,
    minShopLevel: 6,
    statMods: { def: 5, vit: 3 }
  }
];