// Trinket catalog for Arena Legends
// Passive accessories that can modify stats and rewards.

const TRINKETS = [
  {
    key: 'gladiators_token',
    name: "Gladiator's Token",
    type: 'trinket',
    category: 'trinket',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Charm',
    stat: 'Trinket',
    price: 40,
    minShopLevel: 1,
    iconPath: 'assets/images/trinket-icons/trinket2-icon.png',
    statMods: { str: 1 },
    info: 'A simple charm carried by arena hopefuls.',
    infoColor: 'text-gold'
  },
  {
    key: 'gambler_coin',
    name: "Gambler's Coin",
    type: 'trinket',
    category: 'trinket',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Coin',
    stat: 'Trinket',
    price: 45,
    minShopLevel: 1,
    iconPath: 'assets/images/trinket-icons/trinket2-icon.png',
    statMods: { chr: 1 },
    info: 'Luck favours those who dare.',
    infoColor: 'text-gold'
  },
  {
    key: 'blood_carved_ring',
    name: 'Blood-Carved Ring',
    type: 'trinket',
    category: 'trinket',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Ring',
    stat: 'Trinket',
    price: 110,
    minShopLevel: 2,
    iconPath: 'assets/images/trinket-icons/trinket2-icon.png',
    statMods: { str: 1, vit: 1 },
    info: 'A pact sealed in blood.',
    infoColor: 'text-red'
  },
  {
    key: 'seer_eye',
    name: "Seer's Eye",
    type: 'trinket',
    category: 'trinket',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Amulet',
    stat: 'Trinket',
    price: 120,
    minShopLevel: 2,
    iconPath: 'assets/images/trinket-icons/trinket2-icon.png',
    statMods: { mag: 2 },
    info: 'Visions of strikes yet to land.',
    infoColor: 'text-purple'
  },
  {
    key: 'merchant_seal',
    name: "Merchant's Seal",
    type: 'trinket',
    category: 'trinket',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Seal',
    stat: 'Trinket',
    price: 180,
    minShopLevel: 3,
    iconPath: 'assets/images/trinket-icons/trinket2-icon.png',
    statMods: { chr: 2 },
    goldBonus: 0.10,
    xpBonus: 0.05,
    info: 'Traders nod knowingly when they see this.',
    infoColor: 'text-gold'
  },
  {
    key: 'voidwhisper_charm',
    name: 'Voidwhisper Charm',
    type: 'trinket',
    category: 'trinket',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Charm',
    stat: 'Trinket',
    price: 260,
    minShopLevel: 4,
    iconPath: 'assets/images/trinket-icons/trinket2-icon.png',
    statMods: { atk: 2, mag: 1 },
    info: 'Whispers promise power at a price.',
    infoColor: 'text-purple'
  },
  {
    key: 'echoes_of_the_ancients_trinket',
    name: 'Echoes of the Ancients',
    type: 'trinket',
    category: 'trinket',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Amulet',
    stat: 'Trinket',
    price: 480,
    minShopLevel: 5,
    iconPath: 'assets/images/trinket-icons/trinket2-icon.png',
    statMods: { str: 2, atk: 2, vit: 2 },
    goldBonus: 0.15,
    xpBonus: 0.15,
    info: 'Every victory reverberates through time.',
    infoColor: 'text-legendary'
  }
];
