const WEAPONS = [
  // --- COMMON WEAPONS ---
  {
    key: 'rusty_sword',
    name: 'Rusty Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 5,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'training_spear',
    name: 'Training Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 4,
    max: 7,
    stat: 'Damage',
    price: 8,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'old_mace',
    name: 'Old Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 5,
    max: 8,
    stat: 'Damage',
    price: 10,
    minShopLevel: 1,
    statMods: { def: 1 }
  },
  {
    key: 'chipped_dagger',
    name: 'Chipped Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 2,
    max: 5,
    stat: 'Damage',
    price: 6,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'worn_shortbow',
    name: 'Worn Shortbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 3,
    max: 7,
    stat: 'Damage',
    price: 9,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'splintered_staff',
    name: 'Splintered Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 7,
    minShopLevel: 1,
    statMods: { mag: 1 }
  },
  {
    key: 'crude_handaxe',
    name: 'Crude Handaxe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Hand Axe',
    weaponClass: 'Axe',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 11,
    minShopLevel: 1,
    statMods: { str: 1 }
  },
  {
    key: 'militia_sword',
    name: 'Militia Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Shortsword',
    weaponClass: 'Sword',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 12,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'practice_club',
    name: 'Practice Club',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Club',
    weaponClass: 'Hammer',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 5,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'guard_spear',
    name: 'Guard Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 5,
    max: 9,
    stat: 'Damage',
    price: 14,
    minShopLevel: 1,
    statMods: { def: 1 }
  },

  // --- MORE COMMON WEAPONS ---
  {
    key: 'cracked_gladius',
    name: 'Cracked Gladius',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Gladius',
    weaponClass: 'Sword',
    min: 3,
    max: 7,
    stat: 'Damage',
    price: 9,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'stone_maul',
    name: 'Stone Maul',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Maul',
    weaponClass: 'Hammer',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 11,
    minShopLevel: 1,
    statMods: { str: 1 }
  },
  {
    key: 'poachers_bow',
    name: "Poacher's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Shortbow',
    weaponClass: 'Bow',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 10,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'novice_rod',
    name: 'Novice Rod',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Rod',
    weaponClass: 'Spear',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 8,
    minShopLevel: 1,
    statMods: { mag: 1 }
  },
  {
    key: 'jagged_dirk',
    name: 'Jagged Dirk',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Dirk',
    weaponClass: 'Dagger',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 8,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'wooden_spear',
    name: 'Wooden Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 3,
    max: 7,
    stat: 'Damage',
    price: 7,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'training_axe',
    name: 'Training Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Hand Axe',
    weaponClass: 'Axe',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 10,
    minShopLevel: 1,
    statMods: { str: 1 }
  },
  {
    key: 'yardstick_staff',
    name: 'Yardstick Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 2,
    max: 5,
    stat: 'Damage',
    price: 6,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'rope_whip',
    name: 'Rope Whip',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Whip',
    weaponClass: 'Dagger',
    min: 2,
    max: 6,
    stat: 'Damage',
    price: 7,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'cracked_flail',
    name: 'Cracked Flail',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Flail',
    weaponClass: 'Hammer',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 12,
    minShopLevel: 1,
    statMods: { def: 1 }
  },

  // --- UNCOMMON WEAPONS ---
  {
    key: 'iron_axe',
    name: 'Iron Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 7,
    max: 11,
    stat: 'Damage',
    price: 40,
    minShopLevel: 4,
    statMods: { str: 2 }
  },
  {
    key: 'hunter_bow',
    name: "Hunter's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 6,
    max: 10,
    stat: 'Damage',
    price: 45,
    minShopLevel: 2,
    statMods: { chr: 1 }
  },
  {
    key: 'steel_dagger',
    name: 'Steel Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 5,
    max: 9,
    stat: 'Damage',
    price: 38,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'tempered_sword',
    name: 'Tempered Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 50,
    minShopLevel: 2,
    statMods: { atk: 2 }
  },
  {
    key: 'ranger_longbow',
    name: 'Ranger Longbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Longbow',
    weaponClass: 'Bow',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 55,
    minShopLevel: 2,
    statMods: { chr: 2 }
  },
  {
    key: 'duelist_rapier',
    name: 'Duelist Rapier',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Rapier',
    weaponClass: 'Sword',
    min: 6,
    max: 11,
    stat: 'Damage',
    price: 48,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'reinforced_mace',
    name: 'Reinforced Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 52,
    minShopLevel: 2,
    statMods: { str: 2 }
  },
  {
    key: 'skirmisher_spear',
    name: 'Skirmisher Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 46,
    minShopLevel: 2,
    statMods: { atk: 1, def: 1 }
  },
  {
    key: 'twinfang_knives',
    name: 'Twinfang Knives',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Knives',
    weaponClass: 'Dagger',
    min: 6,
    max: 10,
    stat: 'Damage',
    price: 44,
    minShopLevel: 2,
    statMods: { atk: 2 }
  },
  {
    key: 'bonecrusher_flail',
    name: 'Bonecrusher Flail',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Flail',
    weaponClass: 'Hammer',
    min: 8,
    max: 14,
    stat: 'Damage',
    price: 58,
    minShopLevel: 2,
    statMods: { str: 1, vit: 1 }
  },

  // --- MORE UNCOMMON WEAPONS ---
  {
    key: 'soldier_halberd',
    name: 'Soldier Halberd',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Halberd',
    weaponClass: 'Spear',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 56,
    minShopLevel: 2,
    statMods: { str: 1, atk: 1 }
  },
  {
    key: 'iron_longblade',
    name: 'Iron Longblade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Longsword',
    weaponClass: 'Sword',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 49,
    minShopLevel: 2,
    statMods: { atk: 2 }
  },
  {
    key: 'scout_crossbow',
    name: 'Scout Crossbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Crossbow',
    weaponClass: 'Bow',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 53,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'battle_hammer',
    name: 'Battle Hammer',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 9,
    max: 14,
    stat: 'Damage',
    price: 60,
    minShopLevel: 2,
    statMods: { str: 2, def: 1 }
  },
  {
    key: 'assassins_knife',
    name: "Assassin's Knife",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Knife',
    weaponClass: 'Dagger',
    min: 5,
    max: 10,
    stat: 'Damage',
    price: 42,
    minShopLevel: 2,
    statMods: { atk: 2, chr: 1 }
  },
  {
    key: 'thornwood_staff',
    name: 'Thornwood Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 6,
    max: 11,
    stat: 'Damage',
    price: 47,
    minShopLevel: 2,
    statMods: { mag: 2 }
  },
  {
    key: 'warden_pike',
    name: 'Warden Pike',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Pike',
    weaponClass: 'Spear',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 54,
    minShopLevel: 2,
    statMods: { def: 2 }
  },
  {
    key: 'mercenary_sabre',
    name: 'Mercenary Sabre',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Saber',
    weaponClass: 'Sword',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 51,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'breaker_axe',
    name: 'Breaker Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Battleaxe',
    weaponClass: 'Axe',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 57,
    minShopLevel: 2,
    statMods: { str: 2, vit: 1 }
  },
  {
    key: 'pilgrim_bow',
    name: 'Pilgrim Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 6,
    max: 11,
    stat: 'Damage',
    price: 43,
    minShopLevel: 2,
    statMods: { chr: 2 }
  },

  // --- RARE WEAPONS ---
  {
    key: 'soldier_blade',
    name: "Soldier's Blade",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 10,
    max: 15,
    stat: 'Damage',
    price: 90,
    minShopLevel: 7,
    statMods: { atk: 2 }
  },
  {
    key: 'warhammer_of_dawn',
    name: 'Warhammer of Dawn',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 110,
    minShopLevel: 3,
    statMods: { str: 3, def: 1 }
  },
  {
    key: 'spear_of_the_wind',
    name: 'Spear of the Wind',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 11,
    max: 16,
    stat: 'Damage',
    price: 100,
    minShopLevel: 3,
    statMods: { atk: 1, chr: 2 }
  },
  {
    key: 'nightwarden_blade',
    name: 'Nightwarden Blade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 120,
    minShopLevel: 3,
    statMods: { atk: 2, def: 1 }
  },
  {
    key: 'thunderstrike_mace',
    name: 'Thunderstrike Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 3 }
  },
  {
    key: 'dragonspear',
    name: 'Dragonspear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 125,
    minShopLevel: 3,
    statMods: { str: 2, atk: 1 }
  },
  {
    key: 'moonlit_bow',
    name: 'Moonlit Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 10,
    max: 16,
    stat: 'Damage',
    price: 115,
    minShopLevel: 3,
    statMods: { chr: 2, atk: 1 }
  },
  {
    key: 'champion_greatsword',
    name: 'Champion Greatsword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 135,
    minShopLevel: 3,
    statMods: { str: 3, vit: 1 }
  },
  {
    key: 'runed_halberd',
    name: 'Runed Halberd',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Halberd',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 2, mag: 1 }
  },
  {
    key: 'soulpiercer_dagger',
    name: 'Soulpiercer Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 10,
    max: 15,
    stat: 'Damage',
    price: 118,
    minShopLevel: 3,
    statMods: { atk: 2, chr: 1 }
  },

  // --- MORE RARE WEAPONS ---
  {
    key: 'oathkeeper_sword',
    name: 'Oathkeeper Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 138,
    minShopLevel: 3,
    statMods: { atk: 3 }
  },
  {
    key: 'ironstorm_axe',
    name: 'Ironstorm Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 132,
    minShopLevel: 3,
    statMods: { str: 3, vit: 1 }
  },
  {
    key: 'sentinel_bow',
    name: 'Sentinel Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 125,
    minShopLevel: 3,
    statMods: { chr: 2, def: 1 }
  },
  {
    key: 'stormguard_shattermace',
    name: 'Stormguard Shattermace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 140,
    minShopLevel: 3,
    statMods: { str: 3, def: 1 }
  },
  {
    key: 'bloodthorn_daggers',
    name: 'Bloodthorn Daggers',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 11,
    max: 16,
    stat: 'Damage',
    price: 126,
    minShopLevel: 3,
    statMods: { atk: 3, chr: 1 }
  },
  {
    key: 'skybreaker_polearm',
    name: 'Skybreaker Polearm',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Polearm',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 133,
    minShopLevel: 3,
    statMods: { str: 2, atk: 1 }
  },
  {
    key: 'warden_longstaff',
    name: 'Warden Longstaff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 122,
    minShopLevel: 3,
    statMods: { mag: 3, def: 1 }
  },
  {
    key: 'lionheart_blade',
    name: 'Lionheart Blade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 136,
    minShopLevel: 3,
    statMods: { atk: 2, vit: 1 }
  },
  {
    key: 'grim_huntsman_bow',
    name: "Grim Huntsman's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 128,
    minShopLevel: 3,
    statMods: { atk: 1, chr: 2 }
  },
  {
    key: 'spinecrusher_maul',
    name: 'Spinecrusher Maul',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Maul',
    weaponClass: 'Hammer',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 142,
    minShopLevel: 3,
    statMods: { str: 3, vit: 1 }
  },

  // --- EPIC WEAPONS ---
  {
    key: 'shadowfang',
    name: 'Shadowfang',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 180,
    minShopLevel: 10,
    statMods: { atk: 3, chr: 2 }
  },
  {
    key: 'stormreaver',
    name: 'Stormreaver Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'arcanists_staff',
    name: "Arcanist's Staff",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 190,
    minShopLevel: 4,
    statMods: { mag: 4, atk: 1 }
  },
  {
    key: 'bloodsong_saber',
    name: 'Bloodsong Saber',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Saber',
    weaponClass: 'Sword',
    min: 14,
    max: 21,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 1 }
  },
  {
    key: 'voidpiercer_spear',
    name: 'Voidpiercer Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 13,
    max: 20,
    stat: 'Damage',
    price: 205,
    minShopLevel: 4,
    statMods: { atk: 3, mag: 1 }
  },
  {
    key: 'stormcallers_bow',
    name: "Stormcaller's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 14,
    max: 22,
    stat: 'Damage',
    price: 215,
    minShopLevel: 4,
    statMods: { atk: 2, chr: 3 }
  },
  {
    key: 'emberheart_mace',
    name: 'Emberheart Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 220,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'kingslayer_axe',
    name: 'Kingslayer Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 16,
    max: 23,
    stat: 'Damage',
    price: 225,
    minShopLevel: 4,
    statMods: { str: 3, atk: 2 }
  },
  {
    key: 'ghostwalk_daggers',
    name: 'Ghostwalk Daggers',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 200,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 2 }
  },
  {
    key: 'astral_staff',
    name: 'Astral Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 12,
    max: 19,
    stat: 'Damage',
    price: 205,
    minShopLevel: 4,
    statMods: { mag: 5 }
  },

  // --- MORE EPIC WEAPONS ---
  {
    key: 'bloodreign_greatsword',
    name: 'Bloodreign Greatsword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 15,
    max: 23,
    stat: 'Damage',
    price: 230,
    minShopLevel: 4,
    statMods: { str: 4, atk: 2 }
  },
  {
    key: 'thunderspike_lance',
    name: 'Thunderspike Lance',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Lance',
    weaponClass: 'Spear',
    min: 14,
    max: 21,
    stat: 'Damage',
    price: 215,
    minShopLevel: 4,
    statMods: { atk: 3, def: 1 }
  },
  {
    key: 'stormveil_longbow',
    name: 'Stormveil Longbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Longbow',
    weaponClass: 'Bow',
    min: 14,
    max: 22,
    stat: 'Damage',
    price: 220,
    minShopLevel: 4,
    statMods: { atk: 2, chr: 3 }
  },
  {
    key: 'grim_templar_mace',
    name: 'Grim Templar Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 225,
    minShopLevel: 4,
    statMods: { str: 4, def: 2 }
  },
  {
    key: 'soulshard_blades',
    name: 'Soulshard Blades',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 13,
    max: 20,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { atk: 4, chr: 1 }
  },
  {
    key: 'radiant_pike',
    name: 'Radiant Pike',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Pike',
    weaponClass: 'Spear',
    min: 14,
    max: 21,
    stat: 'Damage',
    price: 215,
    minShopLevel: 4,
    statMods: { atk: 2, mag: 2 }
  },
  {
    key: 'warden_guard_axe',
    name: 'Warden Guard Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Battleaxe',
    weaponClass: 'Axe',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 222,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'searing_comet_bow',
    name: 'Searing Comet Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 14,
    max: 22,
    stat: 'Damage',
    price: 218,
    minShopLevel: 4,
    statMods: { atk: 2, chr: 2, mag: 1 }
  },
  {
    key: 'twilight_razor',
    name: 'Twilight Razor',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Saber',
    weaponClass: 'Sword',
    min: 14,
    max: 21,
    stat: 'Damage',
    price: 212,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 1 }
  },
  {
    key: 'voidchant_staff',
    name: 'Voidchant Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 13,
    max: 20,
    stat: 'Damage',
    price: 214,
    minShopLevel: 4,
    statMods: { mag: 5, atk: 1 }
  },

  // --- LEGENDARY WEAPONS ---
  {
    key: 'the_eclipse',
    name: 'The Eclipse',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 400,
    minShopLevel: 12,
    statMods: { str: 7, atk: 12 },
    info: "'They won't even notice...'",
    infoColor: 'text-purple'
  },
  {
    key: 'dragonspine_bow',
    name: 'Dragonspine Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 16,
    max: 24,
    stat: 'Damage',
    price: 390,
    minShopLevel: 5,
    statMods: { atk: 5, chr: 3 }
  },
  {
    key: 'earthshaker',
    name: 'Earthshaker Maul',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 20,
    max: 30,
    stat: 'Damage',
    price: 420,
    minShopLevel: 13,
    statMods: { str: 6, def: 3, vit: 2 },
  },
  {
    key: 'sunbreaker_lance',
    name: 'Sunbreaker Lance',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Lance',
    weaponClass: 'Spear',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 410,
    minShopLevel: 6,
    statMods: { str: 5, atk: 4 },
    info: "'Like my weapon?'",
    infoColor: 'text-purple'
  },
  {
    key: 'voidreaver_blade',
    name: 'Voidreaver Blade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 20,
    max: 28,
    stat: 'Damage',
    price: 430,
    minShopLevel: 6,
    statMods: { atk: 8, mag: 4 }
  },
  {
    key: 'phoenix_talon',
    name: 'Phoenix Talon',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 400,
    minShopLevel: 5,
    statMods: { atk: 6, chr: 4 }
  },
  {
    key: 'worldsplitter_axe',
    name: 'Worldsplitter Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 21,
    max: 30,
    stat: 'Damage',
    price: 440,
    minShopLevel: 6,
    statMods: { str: 7, vit: 3 }
  },
  {
    key: 'crownslayer_daggers',
    name: 'Crownslayer Daggers',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 415,
    minShopLevel: 6,
    statMods: { atk: 7, chr: 3 }
  },
  {
    key: 'starfall_bow',
    name: 'Starfall Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 405,
    minShopLevel: 5,
    statMods: { atk: 5, chr: 4, mag: 2 }
  },
  {
    key: 'titans_grip_maul',
    name: "Titan's Grip Maul",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Maul',
    weaponClass: 'Hammer',
    min: 22,
    max: 32,
    stat: 'Damage',
    price: 450,
    minShopLevel: 6,
    statMods: { str: 8, def: 4, vit: 3 }
  },

  // --- MORE LEGENDARY WEAPONS ---
  {
    key: 'grim_oathblade',
    name: 'Grim Oathblade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 20,
    max: 29,
    stat: 'Damage',
    price: 435,
    minShopLevel: 6,
    statMods: { str: 7, atk: 8 },
    info: "'Sworn once. Broken never.'",
    infoColor: 'text-purple'
  },
  {
    key: 'heartsear_longbow',
    name: 'Heartsear Longbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Longbow',
    weaponClass: 'Bow',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 420,
    minShopLevel: 5,
    statMods: { atk: 6, chr: 4 },
    info: "'If it sings, someone dies.'",
    infoColor: 'text-purple'
  },
  {
    key: 'oblivion_fang',
    name: 'Oblivion Fang',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 410,
    minShopLevel: 5,
    statMods: { atk: 8, chr: 3 }
  },
  {
    key: 'colossus_breaker',
    name: 'Colossus Breaker',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Maul',
    weaponClass: 'Hammer',
    min: 22,
    max: 33,
    stat: 'Damage',
    price: 460,
    minShopLevel: 6,
    statMods: { str: 9, vit: 3, def: 3 }
  },
  {
    key: 'dawnguard_pike',
    name: 'Dawnguard Pike',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Pike',
    weaponClass: 'Spear',
    min: 20,
    max: 28,
    stat: 'Damage',
    price: 425,
    minShopLevel: 6,
    statMods: { str: 5, atk: 5, def: 2 }
  },
  {
    key: 'seraphic_glaive',
    name: 'Seraphic Glaive',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Glaive',
    weaponClass: 'Spear',
    min: 20,
    max: 28,
    stat: 'Damage',
    price: 432,
    minShopLevel: 6,
    statMods: { atk: 6, mag: 4 }
  },
  {
    key: 'nightfall_regalia',
    name: 'Nightfall Regalia',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 19,
    max: 28,
    stat: 'Damage',
    price: 418,
    minShopLevel: 5,
    statMods: { atk: 7, chr: 3 },
    info: "'Royal blood washes off the easiest.'",
    infoColor: 'text-purple'
  },
  {
    key: 'ashen_tempest_bow',
    name: 'Ashen Tempest Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 412,
    minShopLevel: 5,
    statMods: { atk: 6, chr: 3, mag: 2 }
  },
  {
    key: 'fatecarver_axes',
    name: 'Fatecarver Axes',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Axes',
    weaponClass: 'Axe',
    min: 21,
    max: 30,
    stat: 'Damage',
    price: 445,
    minShopLevel: 6,
    statMods: { str: 7, atk: 4 }
  },
  {
    key: 'sunsorrow_morningstar',
    name: 'Sunsorrow Morningstar',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Morningstar',
    weaponClass: 'Hammer',
    min: 21,
    max: 30,
    stat: 'Damage',
    price: 438,
    minShopLevel: 6,
    statMods: { str: 7, vit: 2, def: 2 }
  }
];
