const WEAPONS = [
  // --- COMMON WEAPONS ---
  {
    key: 'rusty_sword',
    name: 'Rusty Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 5,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'training_spear',
    name: 'Training Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 4,
    max: 7,
    stat: 'Damage',
    price: 8,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'old_mace',
    name: 'Old Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 5,
    max: 8,
    stat: 'Damage',
    price: 10,
    minShopLevel: 1,
    statMods: { def: 1 }
  },
  {
    key: 'chipped_dagger',
    name: 'Chipped Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 2,
    max: 5,
    stat: 'Damage',
    price: 6,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'worn_shortbow',
    name: 'Worn Shortbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 3,
    max: 7,
    stat: 'Damage',
    price: 9,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'splintered_staff',
    name: 'Splintered Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 7,
    minShopLevel: 1,
    statMods: { mag: 1 }
  },
  {
    key: 'crude_handaxe',
    name: 'Crude Handaxe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Hand Axe',
    weaponClass: 'Axe',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 11,
    minShopLevel: 1,
    statMods: { str: 1 }
  },
  {
    key: 'militia_sword',
    name: 'Militia Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Shortsword',
    weaponClass: 'Sword',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 12,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'practice_club',
    name: 'Practice Club',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Club',
    weaponClass: 'Hammer',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 5,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'guard_spear',
    name: 'Guard Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 5,
    max: 9,
    stat: 'Damage',
    price: 14,
    minShopLevel: 1,
    statMods: { def: 1 }
  },

  // --- UNCOMMON WEAPONS ---
  {
    key: 'iron_axe',
    name: 'Iron Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 7,
    max: 11,
    stat: 'Damage',
    price: 40,
    minShopLevel: 2,
    statMods: { str: 2 }
  },
  {
    key: 'hunter_bow',
    name: "Hunter's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 6,
    max: 10,
    stat: 'Damage',
    price: 45,
    minShopLevel: 2,
    statMods: { chr: 1 }
  },
  {
    key: 'steel_dagger',
    name: 'Steel Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 5,
    max: 9,
    stat: 'Damage',
    price: 38,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'tempered_sword',
    name: 'Tempered Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 50,
    minShopLevel: 2,
    statMods: { atk: 2 }
  },
  {
    key: 'ranger_longbow',
    name: 'Ranger Longbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Longbow',
    weaponClass: 'Bow',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 55,
    minShopLevel: 2,
    statMods: { chr: 2 }
  },
  {
    key: 'duelist_rapier',
    name: 'Duelist Rapier',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Rapier',
    weaponClass: 'Sword',
    min: 6,
    max: 11,
    stat: 'Damage',
    price: 48,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'reinforced_mace',
    name: 'Reinforced Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 52,
    minShopLevel: 2,
    statMods: { str: 2 }
  },
  {
    key: 'skirmisher_spear',
    name: 'Skirmisher Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 46,
    minShopLevel: 2,
    statMods: { atk: 1, def: 1 }
  },
  {
    key: 'twinfang_knives',
    name: 'Twinfang Knives',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Knives',
    weaponClass: 'Dagger',
    min: 6,
    max: 10,
    stat: 'Damage',
    price: 44,
    minShopLevel: 2,
    statMods: { atk: 2 }
  },
  {
    key: 'bonecrusher_flail',
    name: 'Bonecrusher Flail',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Flail',
    weaponClass: 'Hammer',
    min: 8,
    max: 14,
    stat: 'Damage',
    price: 58,
    minShopLevel: 2,
    statMods: { str: 1, vit: 1 }
  },

  // --- RARE WEAPONS ---
  {
    key: 'soldier_blade',
    name: "Soldier's Blade",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 10,
    max: 15,
    stat: 'Damage',
    price: 90,
    minShopLevel: 3,
    statMods: { atk: 2 }
  },
  {
    key: 'warhammer_of_dawn',
    name: 'Warhammer of Dawn',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 110,
    minShopLevel: 3,
    statMods: { str: 3, def: 1 }
  },
  {
    key: 'spear_of_the_wind',
    name: 'Spear of the Wind',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 11,
    max: 16,
    stat: 'Damage',
    price: 100,
    minShopLevel: 3,
    statMods: { atk: 1, chr: 2 }
  },
  {
    key: 'nightwarden_blade',
    name: 'Nightwarden Blade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 120,
    minShopLevel: 3,
    statMods: { atk: 2, def: 1 }
  },
  {
    key: 'thunderstrike_mace',
    name: 'Thunderstrike Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 3 }
  },
  {
    key: 'dragonspear',
    name: 'Dragonspear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 125,
    minShopLevel: 3,
    statMods: { str: 2, atk: 1 }
  },
  {
    key: 'moonlit_bow',
    name: 'Moonlit Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 10,
    max: 16,
    stat: 'Damage',
    price: 115,
    minShopLevel: 3,
    statMods: { chr: 2, atk: 1 }
  },
  {
    key: 'champion_greatsword',
    name: 'Champion Greatsword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 135,
    minShopLevel: 3,
    statMods: { str: 3, vit: 1 }
  },
  {
    key: 'runed_halberd',
    name: 'Runed Halberd',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Halberd',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 2, mag: 1 }
  },
  {
    key: 'soulpiercer_dagger',
    name: 'Soulpiercer Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 10,
    max: 15,
    stat: 'Damage',
    price: 118,
    minShopLevel: 3,
    statMods: { atk: 2, chr: 1 }
  },

  // --- EPIC WEAPONS ---
  {
    key: 'shadowfang',
    name: 'Shadowfang',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 180,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 2 }
  },
  {
    key: 'stormreaver',
    name: 'Stormreaver Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'arcanists_staff',
    name: "Arcanist's Staff",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 190,
    minShopLevel: 4,
    statMods: { mag: 4, atk: 1 }
  },
  {
    key: 'bloodsong_saber',
    name: 'Bloodsong Saber',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Saber',
    weaponClass: 'Sword',
    min: 14,
    max: 21,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 1 }
  },
  {
    key: 'voidpiercer_spear',
    name: 'Voidpiercer Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 13,
    max: 20,
    stat: 'Damage',
    price: 205,
    minShopLevel: 4,
    statMods: { atk: 3, mag: 1 }
  },
  {
    key: 'stormcallers_bow',
    name: "Stormcaller's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 14,
    max: 22,
    stat: 'Damage',
    price: 215,
    minShopLevel: 4,
    statMods: { atk: 2, chr: 3 }
  },
  {
    key: 'emberheart_mace',
    name: 'Emberheart Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 220,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'kingslayer_axe',
    name: 'Kingslayer Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 16,
    max: 23,
    stat: 'Damage',
    price: 225,
    minShopLevel: 4,
    statMods: { str: 3, atk: 2 }
  },
  {
    key: 'ghostwalk_daggers',
    name: 'Ghostwalk Daggers',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 200,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 2 }
  },
  {
    key: 'astral_staff',
    name: 'Astral Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 12,
    max: 19,
    stat: 'Damage',
    price: 205,
    minShopLevel: 4,
    statMods: { mag: 5 }
  },

  // --- LEGENDARY WEAPONS ---
  {
    key: 'the_eclipse',
    name: 'The Eclipse',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 400,
    minShopLevel: 5,
    statMods: { str: 7, atk: 12 },
    info: "'They won't even notice...'",
    infoColor: 'text-purple'
  },
  {
    key: 'dragonspine_bow',
    name: 'Dragonspine Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 16,
    max: 24,
    stat: 'Damage',
    price: 390,
    minShopLevel: 5,
    statMods: { atk: 5, chr: 3 }
  },
  {
    key: 'earthshaker',
    name: 'Earthshaker Maul',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 20,
    max: 30,
    stat: 'Damage',
    price: 420,
    minShopLevel: 6,
    statMods: { str: 6, def: 3, vit: 2 },
  },
  {
    key: 'sunbreaker_lance',
    name: 'Sunbreaker Lance',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Lance',
    weaponClass: 'Spear',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 410,
    minShopLevel: 6,
    statMods: { str: 5, atk: 4 },
    info: "'Like my weapon?'",
    infoColor: 'text-purple'
  },
  {
    key: 'voidreaver_blade',
    name: 'Voidreaver Blade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 20,
    max: 28,
    stat: 'Damage',
    price: 430,
    minShopLevel: 6,
    statMods: { atk: 8, mag: 4 }
  },
  {
    key: 'phoenix_talon',
    name: 'Phoenix Talon',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 400,
    minShopLevel: 5,
    statMods: { atk: 6, chr: 4 }
  },
  {
    key: 'worldsplitter_axe',
    name: 'Worldsplitter Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 21,
    max: 30,
    stat: 'Damage',
    price: 440,
    minShopLevel: 6,
    statMods: { str: 7, vit: 3 }
  },
  {
    key: 'crownslayer_daggers',
    name: 'Crownslayer Daggers',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 415,
    minShopLevel: 6,
    statMods: { atk: 7, chr: 3 }
  },
  {
    key: 'starfall_bow',
    name: 'Starfall Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 405,
    minShopLevel: 5,
    statMods: { atk: 5, chr: 4, mag: 2 }
  },
  {
    key: 'titans_grip_maul',
    name: "Titan's Grip Maul",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Maul',
    weaponClass: 'Hammer',
    min: 22,
    max: 32,
    stat: 'Damage',
    price: 450,
    minShopLevel: 6,
    statMods: { str: 8, def: 4, vit: 3 }
  }
];